### PR TITLE
Better API for PID.Ask

### PR DESCRIPTION
**Pull request by dtravin**

### CODE REVIEW

**Comment by rogeralsing** [comment]
Is there a reason why the result values are reutrned as `error, response` instead of `response, error`?
I have never seen that order before, but then again, I started Go this year so it might just be that.

**Comment by rogeralsing** [comment]
Also, would it make sense to use the `context` package to provide the timeout support for `Ask` ?
https://golang.org/src/context/context.go?s=13917:13994#L426

**Comment by dtravin** [comment]
"By convention, errors are the last return value and have type error, a built-in interface."
My bad

**Comment by dtravin** [comment]
Give me an example API you want to achieve with context.
Are you trying to hide the deferred Stop() from application code in such way ?

**Comment by rogeralsing** [comment]
I was mostly thinking that there might be some more idiomatic way to handle timeouts in Go.
Just so that GAM don't introduce some made up concept (Response) if there is a better way to handle it.

btw. I have adapted the tests to use the new Ask API, love it! much more straight forward now.

**Pull request merged**
